version: '1'
services:
  proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
  jenkins:
    image: killercentury/jenkins-dind
    environment:
      VIRTUAL_HOST: jenkins.hjohnsondev.com
      VIRTUAL_PORT: 8080
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - proxy