nginx:
  image: jwilder/nginx-proxy
  restart: always
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - /root/certs:/etc/nginx/certs
  - /var/run/docker.sock:/tmp/docker.sock:ro

jenkins:
  image: jenkins-img
  restart: always
  volumes:
  - jenkins_home:/var/jenkins_home
  - test_reports:/var/local/test_reports
  - /var/run/docker.sock:/var/run/docker.sock
  environment:
  - VIRTUAL_HOST=jenkins.livehen.com
  - VIRTUAL_PORT=8080

postgres:
  image: postgres
  restart: always
  volumes:
  - jira_postgres:/var/lib/postgresql/data postgres

jira:
  image: cptactionhank/atlassian-jira:latest
  restart: always
  volumes:
  - jira_home:/var/atlassian/jira
  environment:
  - VIRTUAL_HOST=jira.livehen.com
  - VIRTUAL_PORT=8080
  - X_PROXY_NAME=jira.livehen.com
  - X_PROXY_PORT=443
  - X_PROXY_SCHEME=https
  links:
  - postgres
