nginx:
  image: jwilder/nginx-proxy
  restart: always
  ports:
  - "80:80"
  - "443:443"
  volumes:
  - /root/certs:/etc/nginx/certs
  - /var/run/docker.sock:/tmp/docker.sock:ro

jenkins:
  image: jenkins-img
  restart: always
  volumes:
  - jenkins_home:/var/lib/jenkins
  - test_reports:/var/local/test_reports
  - /var/run/docker.sock:/var/run/docker.sock
  environment:
  - VIRTUAL_HOST=jenkins.livehen.com
  - VIRTUAL_PORT=8080
